apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
  namespace: cnpg-system
spec:
  instances: 3

  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  superuserSecret:
    name: pg-super-user-creds

  bootstrap:
    initdb:
      database: app
      owner: pickupp
      secret:
        name: app-secret

  # Require 1Gi of space
  storage:
    size: 1Gi
