apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: dev-pg-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  autoRestart:
    enabled: true
  config:
    tasks.max: 1
    plugin.name: pgoutput
    slot.name: debezium_dev
    database.hostname: host.minikube.internal
    database.port: 5432
    database.user: pickupp
    database.password: "QcgALyevFSKDRXaUw4MGhL4UptY3QmCJ"
    database.dbname: dev
    topic.prefix: postgres.dev
    schema.exclude.list: public
    table.exclude.list: "\\w+\\._prisma_migrations,\\w+\\.goose_db_version,\\w+\\.SequelizeMeta"
    key.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    transforms: "changeTopicCase,fixChangeTopicCase,Reroute,changeValueCase"
    transforms.changeTopicCase.type: "com.github.jcustenborder.kafka.connect.transform.common.ChangeTopicCase"
    transforms.changeTopicCase.from: "UPPER_CAMEL"
    transforms.changeTopicCase.to: "LOWER_UNDERSCORE"
    transforms.fixChangeTopicCase.type: "org.apache.kafka.connect.transforms.RegexRouter"
    transforms.fixChangeTopicCase.regex: "(\\w+)\\.(\\w+)\\.(\\w+)\\._(\\w+)"
    transforms.fixChangeTopicCase.replacement: "$1.$2.$3.$4"
    transforms.Reroute.type: "io.debezium.transforms.ByLogicalTableRouter"
    transforms.Reroute.topic.regex: "(\\w+)\\.\\w+\\.(\\w+)\\.(\\w+)"
    transforms.Reroute.topic.replacement: "$1.$2.$3"
    transforms.changeValueCase.type: "com.github.jcustenborder.kafka.connect.transform.common.ChangeCase$Value"
    transforms.changeValueCase.from: "LOWER_CAMEL"
    transforms.changeValueCase.to: "LOWER_UNDERSCORE"
