apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: jdbc-sink-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 1
  autoRestart: 
    enabled: true
  config:
    tasks.max: 1
    connection.url: jdbc:postgresql://host.minikube.internal:58388/postgres
    connection.user: postgres
    connection.password: admin
    # topics: postgres.agent.crews
    topics.regex: postgres\.agent.*
    key.converter: "io.confluent.connect.avro.AvroConverter"
    key.converter.schema.registry.url: http://schema-registry:8081
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: http://schema-registry:8081
    transforms: unwrap
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    auto.create: true
    auto.evolve: true
    insert.mode: upsert
    pk.mode: record_key
    pk.fields: id
