apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: jdbc-sink-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 1
  autoRestart: 
    enabled: true
  config:
    tasks.max: 1
    connection.url: jdbc:postgresql://host.minikube.internal:51237/app
    connection.user: pickupp
    connection.password: app
    # topics: postgres.agent.crews
    topics.regex: postgres\.agent.*
    key.converter: "io.confluent.connect.avro.AvroConverter"
    key.converter.schema.registry.url: http://schema-registry:8081
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: http://schema-registry:8081
    transforms: "unwrap,topicNameChange"
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: false
    transforms.topicNameChange.type: "org.apache.kafka.connect.transforms.RegexRouter"
    transforms.topicNameChange.regex: "(\\w+)\\.(\\w+)\\.(\\w+)"
    transforms.topicNameChange.replacement: "$2_$3"
    delete.enabled: true
    auto.create: true
    auto.evolve: true
    insert.mode: upsert
    pk.mode: record_key
    pk.fields: id
