apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: local-pg-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  autoRestart:
    enabled: true
  config:
    tasks.max: 1
    plugin.name: pgoutput
    slot.name: debezium_dev
    database.hostname: host.minikube.internal
    database.port: 5432
    database.user: pickupp
    database.password: ""
    database.dbname: dev
    topic.prefix: postgres.local
    schema.exclude.list: public
    table.exclude.list: "\\w+\\._prisma_migrations,\\w+\\.goose_db_version,\\w+\\.SequelizeMeta"
