apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: strimzi-operator
  namespace: kafka
resources:
- strimzi-operator.yaml
# - kafka-cluster.yaml
# - kafka-connect.yaml
# - kafka-ui.yaml
# - file-topic.yaml
# - file-connector.yaml
# - local-pg-connector.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka-cluster
  namespace: kafka
resources:
  - kafka-cluster.yaml
spec:
  dependsOn:
    - name: strimzi-operator
