apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: strimzi-operator
  namespace: kafka
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/strimzi
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: strimzi-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/kafka-cluster
  prune: true
  wait: true
