apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: strimzi
  namespace: kafka
spec:
  interval: 1m
  url: https://strimzi.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi-operator
  namespace: kafka
spec:
  interval: 5m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: kafka
      interval: 1m
