apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-operator
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/cloudnative-pg
  prune: true
  wait: true
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-super-user-creds
  namespace: cnpg-system
type: kubernetes.io/basic-auth
stringData:
  username: postgres      # required field for kubernetes.io/basic-auth
  password: admin # required field for kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: cnpg-system
type: kubernetes.io/basic-auth
stringData:
  username: pickupp      # required field for kubernetes.io/basic-auth
  password: app # required field for kubernetes.io/basic-auth
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pg-cluster
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cloudnative-pg-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/postgres-cluster
  prune: true
  wait: true
