apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: strimzi-operator
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/strimzi
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka-cluster
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: strimzi-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/kafka-cluster
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka-connect
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: kafka-cluster
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/kafka-connect
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka-ui
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: kafka-cluster
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/kafka-ui
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka-connectors
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: kafka-connect
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/kafka-connectors
  prune: true
  wait: true
