apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  namespace: kafka
  annotations:
#  # use-connector-resources configures this KafkaConnect
#  # to use KafkaConnector resources to avoid
#  # needing to call the Connect REST API directly
   strimzi.io/use-connector-resources: "true"
spec:
  version: 3.4.0
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9093
  logging:
    type: inline
    loggers:
      connect.root.logger.level: "INFO"
  tls:
    trustedCertificates:
      - secretName: my-cluster-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    key.converter.schemas.enable: true
    value.converter.schemas.enable: true
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  build:
    output:
      type: docker
      # This image will last only for 24 hours and might be overwritten by other users
      # Strimzi will use this tag to push the image. But it will use the digest to pull
      # the container image to make sure it pulls exactly the image we just built. So
      # it should not happen that you pull someone else's container image. However, we
      # recommend changing this to your own container registry or using a different
      # image name for any other than demo purposes.
      image: ttl.sh/strimzi-connect-example-3.4.0:24h
    plugins:
      - name: kafka-connect-file
        artifacts:
          - type: maven
            group: org.apache.kafka
            artifact: connect-file
            version: 3.4.0
      - name: avro-converter
        artifacts:
          - type: maven
            repository: https://packages.confluent.io/maven
            group: io.confluent
            artifact: kafka-connect-avro-converter
            version: 7.4.0
      - name: debezium-pg-source-tgz
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.2.1.Final/debezium-connector-postgres-2.2.1.Final-plugin.tar.gz
            sha512sum: 0bcb0e99f1beba4351fbd18962fee364663fc58914eae302c0dd2a52b8fbefd2a5ec10da909fd0f49207293d5c86f90ec7c0a6c90947c97285ea61f229acdaeb
      # - name: debezium-pg-connector
      #   artifacts:
      #     - type: maven
      #       group: io.debezium
      #       artifact: debezium-connector-postgres
      #       version: 2.2.1.Final
      - name: kakfa-connect-transform-common
        artifacts:
          - type: maven
            group: com.github.jcustenborder.kafka.connect
            artifact: kafka-connect-transform-common
            version: 0.1.0.14
      - name: confluent-jdbc-connector
        artifacts:
          - type: maven
            group: io.confluent
            repository: https://packages.confluent.io/maven
            artifact: kafka-connect-jdbc
            version: 10.7.0
