apiVersion: v1
kind: Secret
metadata:
  name: pg-super-user-creds
  namespace: cnpg-system
type: kubernetes.io/basic-auth
stringData:
  username: postgres      # required field for kubernetes.io/basic-auth
  password: admin # required field for kubernetes.io/basic-auth
