apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: schema-registry
  namespace: kafka
spec:
  interval: 1m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: schema-registry
  namespace: kafka
spec:
  interval: 5m
  chart:
    spec:
      chart: schema-registry
      version: '11.0.0'
      sourceRef:
        kind: HelmRepository
        name: schema-registry
        namespace: kafka
      interval: 1m
